//* Productos 
export const MOSTRAR_PRODUCTOS = "MOSTRAR_PRODUCTOS";
export const ERROR_PRODUCTO = "ERROR_PRODUCTO";
export const LIMPIAR_PRODUCTOS = "LIMPIAR_PRODUCTOS";
export const MOSTRAR_PRODUCTO_UNICO = "MOSTRAR_PRODUCTO_UNICO";

//* Noticias 
export const MOSTRAR_NOTICIAS = "MOSTRAR_NOTICIAS";
export const ERROR_NOTICIA = "ERROR_NOTICIA";
export const LIMPIAR_NOTICIAS = "LIMPIAR_NOTICIAS";
export const MOSTRAR_NOTICIA_UNICA = "MOSTRAR_NOTICIA_UNICA";

//* Puntos 
export const MOSTRAR_PUNTOS = "MOSTRAR_PUNTOS";
export const ERROR_PUNTO = "ERROR_PUNTO";
export const LIMPIAR_PUNTOS = "LIMPIAR_PUNTOS";
export const MOSTRAR_PUNTO_UNICO = "MOSTRAR_PUNTO_UNICO";

//* Cronograma
export const MOSTRAR_CRONOGRAMA = "MOSTRAR_CRONOGRAMA";
export const ERROR_CRONOGRAMA = "ERROR_CRONOGRAMA";
export const LIMPIAR_CRONOGRAMA = "LIMPIAR_CRONOGRAMA";

//* Programas
export const MOSTRAR_PROGRAMAS = "MOSTRAR_PROGRAMAS";
export const ERROR_PROGRAMAS = "ERROR_PROGRAMAS";
export const LIMPIAR_PROGRAMAS = "LIMPIAR_PROGRAMAS";

export const MOSTRAR_PROGRAMA_VIVO = "MOSTRAR_PROGRAMA_VIVO";
export const LIMPIAR_PROGRAMA_VIVO = "LIMPIAR_PROGRAMA_VIVO";
export const ERROR_PROGRAMA_VIVO = "ERROR_PROGRAMA_VIVO";